spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true

server:
  port: 8081